apiVersion: v1
kind: Service
metadata:
  name: secure-cicd-demo
  labels:
    app: secure-cicd-demo
spec:
  # Use LoadBalancer for cloud (EKS/AKS/GKE)
  # Use NodePort for Minikube local practice
  type: NodePort
  selector:
    app: secure-cicd-demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30080     # access via http://MINIKUBE_IP:30080
